('FWC 0', 'FWC'),
('FWC 1', 'FWC'),
('FWC 2', 'FWC'),
('FWC 3', 'FWC'),
('FWC 4', 'FWC'),
('FWC 5', 'FWC'),
('FWC 6', 'FWC'),
('FWC 7', 'FWC'),
('FWC 8', 'FWC'),
('FWC 9', 'FWC'),
('FWC 10', 'FWC'),
('FWC 11', 'FWC'),
('FWC 12', 'FWC'),
('FWC 13', 'FWC'),
('FWC 14', 'FWC'),
('FWC 15', 'FWC'),
('FWC 16', 'FWC'),
('FWC 17', 'FWC'),
('FWC 18', 'FWC'),
('FWC 19', 'FWC'),
('CC1', 'Coca-Cola'),
('CC2', 'Coca-Cola'),
('CC3', 'Coca-Cola'),
('CC4', 'Coca-Cola'),
('CC5', 'Coca-Cola'),
('CC6', 'Coca-Cola'),
('CC7', 'Coca-Cola'),
('CC8', 'Coca-Cola'),
('CC9', 'Coca-Cola'),
('CC10', 'Coca-Cola'),
('CC11', 'Coca-Cola'),
('CC12', 'Coca-Cola'),
('CC13', 'Coca-Cola'),
('CC14', 'Coca-Cola'),
('MEX 1', 'México'),
('MEX 2', 'México'),
('MEX 3', 'México'),
('MEX 4', 'México'),
('MEX 5', 'México'),
('MEX 6', 'México'),
('MEX 7', 'México'),
('MEX 8', 'México'),
('MEX 9', 'México'),
('MEX 10', 'México'),
('MEX 11', 'México'),
('MEX 12', 'México'),
('MEX 13', 'México'),
('MEX 14', 'México'),
('MEX 15', 'México'),
('MEX 16', 'México'),
('MEX 17', 'México'),
('MEX 18', 'México'),
('MEX 19', 'México'),
('MEX 20', 'México'),
('KSI 1', 'Coreia do Sul'),
('KSI 2', 'Coreia do Sul'),
('KSI 3', 'Coreia do Sul'),
('KSI 4', 'Coreia do Sul'),
('KSI 5', 'Coreia do Sul'),
('KSI 6', 'Coreia do Sul'),
('KSI 7', 'Coreia do Sul'),
('KSI 8', 'Coreia do Sul'),
('KSI 9', 'Coreia do Sul'),
('KSI 10', 'Coreia do Sul'),
('KSI 11', 'Coreia do Sul'),
('KSI 12', 'Coreia do Sul'),
('KSI 13', 'Coreia do Sul'),
('KSI 14', 'Coreia do Sul'),
('KSI 15', 'Coreia do Sul'),
('KSI 16', 'Coreia do Sul'),
('KSI 17', 'Coreia do Sul'),
('KSI 18', 'Coreia do Sul'),
('KSI 19', 'Coreia do Sul'),
('KSI 20', 'Coreia do Sul'),
('CZE 1', 'Tchéquia'),
('CZE 2', 'Tchéquia'),
('CZE 3', 'Tchéquia'),
('CZE 4', 'Tchéquia'),
('CZE 5', 'Tchéquia'),
('CZE 6', 'Tchéquia'),
('CZE 7', 'Tchéquia'),
('CZE 8', 'Tchéquia'),
('CZE 9', 'Tchéquia'),
('CZE 10', 'Tchéquia'),
('CZE 11', 'Tchéquia'),
('CZE 12', 'Tchéquia'),
('CZE 13', 'Tchéquia'),
('CZE 14', 'Tchéquia'),
('CZE 15', 'Tchéquia'),
('CZE 16', 'Tchéquia'),
('CZE 17', 'Tchéquia'),
('CZE 18', 'Tchéquia'),
('CZE 19', 'Tchéquia'),
('CZE 20', 'Tchéquia'),
('RSA 1', 'África do Sul'),
('RSA 2', 'África do Sul'),
('RSA 3', 'África do Sul'),
('RSA 4', 'África do Sul'),
('RSA 5', 'África do Sul'),
('RSA 6', 'África do Sul'),
('RSA 7', 'África do Sul'),
('RSA 8', 'África do Sul'),
('RSA 9', 'África do Sul'),
('RSA 10', 'África do Sul'),
('RSA 11', 'África do Sul'),
('RSA 12', 'África do Sul'),
('RSA 13', 'África do Sul'),
('RSA 14', 'África do Sul'),
('RSA 15', 'África do Sul'),
('RSA 16', 'África do Sul'),
('RSA 17', 'África do Sul'),
('RSA 18', 'África do Sul'),
('RSA 19', 'África do Sul'),
('RSA 20', 'África do Sul'),
('SUI 1', 'Suiça'),
('SUI 2', 'Suiça'),
('SUI 3', 'Suiça'),
('SUI 4', 'Suiça'),
('SUI 5', 'Suiça'),
('SUI 6', 'Suiça'),
('SUI 7', 'Suiça'),
('SUI 8', 'Suiça'),
('SUI 9', 'Suiça'),
('SUI 10', 'Suiça'),
('SUI 11', 'Suiça'),
('SUI 12', 'Suiça'),
('SUI 13', 'Suiça'),
('SUI 14', 'Suiça'),
('SUI 15', 'Suiça'),
('SUI 16', 'Suiça'),
('SUI 17', 'Suiça'),
('SUI 18', 'Suiça'),
('SUI 19', 'Suiça'),
('SUI 20', 'Suiça'),
('CAN 1', 'Canadá'),
('CAN 2', 'Canadá'),
('CAN 3', 'Canadá'),
('CAN 4', 'Canadá'),
('CAN 5', 'Canadá'),
('CAN 6', 'Canadá'),
('CAN 7', 'Canadá'),
('CAN 8', 'Canadá'),
('CAN 9', 'Canadá'),
('CAN 10', 'Canadá'),
('CAN 11', 'Canadá'),
('CAN 12', 'Canadá'),
('CAN 13', 'Canadá'),
('CAN 14', 'Canadá'),
('CAN 15', 'Canadá'),
('CAN 16', 'Canadá'),
('CAN 17', 'Canadá'),
('CAN 18', 'Canadá'),
('CAN 19', 'Canadá'),
('CAN 20', 'Canadá'),
('BIH 1', 'Bósnia'),
('BIH 2', 'Bósnia'),
('BIH 3', 'Bósnia'),
('BIH 4', 'Bósnia'),
('BIH 5', 'Bósnia'),
('BIH 6', 'Bósnia'),
('BIH 7', 'Bósnia'),
('BIH 8', 'Bósnia'),
('BIH 9', 'Bósnia'),
('BIH 10', 'Bósnia'),
('BIH 11', 'Bósnia'),
('BIH 12', 'Bósnia'),
(BIH 13', 'Bósnia'),
('BIH 14', 'Bósnia'),
('BIH 15', 'Bósnia'),
('BIH 16', 'Bósnia'),
('BIH 17', 'Bósnia'),
('BIH 18', 'Bósnia'),
('BIH 19', 'Bósnia'),
('BIH 20', 'Bósnia'),
('QAT 1', 'Qatar'),
('QAT 2', 'Qatar'),
('QAT 3', 'Qatar'),
('QAT 4', 'Qatar'),
('QAT 5', 'Qatar'),
('QAT 6', 'Qatar'),
('QAT 7', 'Qatar'),
('QAT 8', 'Qatar'),
('QAT 9', 'Qatar'),
('QAT 10', 'Qatar'),
('QAT 11', 'Qatar'),
('QAT 12', 'Qatar'),
('QAT 13', 'Qatar'),
('QAT 14', 'Qatar'),
('QAT 15', 'Qatar'),
('QAT 16', 'Qatar'),
('QAT 17', 'Qatar'),
('QAT 18', 'Qatar'),
('QAT 19', 'Qatar'),
('QAT 20', 'Qatar'),
('BRA 1', 'Brasil'),
('BRA 2', 'Brasil'),
('BRA 3', 'Brasil'),
('BRA 4', 'Brasil'),
('BRA 5', 'Brasil'),
('BRA 6', 'Brasil'),
('BRA 7', 'Brasil'),
('BRA 8', 'Brasil'),
('BRA 9', 'Brasil'),
('BRA 10', 'Brasil'),
('BRA 11', 'Brasil'),
('BRA 12', 'Brasil'),
('BRA 13', 'Brasil'),
('BRA 14', 'Brasil'),
('BRA 15', 'Brasil'),
('BRA 16', 'Brasil'),
('BRA 17', 'Brasil'),
('BRA 18', 'Brasil'),
('BRA 19', 'Brasil'),
('BRA 20', 'Brasil'),
('MAR 1', 'Marrocos'),
('MAR 2', 'Marrocos'),
('MAR 3', 'Marrocos'),
('MAR 4', 'Marrocos'),
('MAR 5', 'Marrocos'),
('MAR 6', 'Marrocos'),
('MAR 7', 'Marrocos'),
('MAR 8', 'Marrocos'),
('MAR 9', 'Marrocos'),
('MAR 10', 'Marrocos'),
('MAR 11', 'Marrocos'),
('MAR 12', 'Marrocos'),
('MAR 13', 'Marrocos'),
('MAR 14', 'Marrocos'),
('MAR 15', 'Marrocos'),
('MAR 16', 'Marrocos'),
('MAR 17', 'Marrocos'),
('MAR 18', 'Marrocos'),
('MAR 19', 'Marrocos'),
('MAR 20', 'Marrocos'),
('SCO 1', 'Escócia'),
('SCO 2', 'Escócia'),
('SCO 3', 'Escócia'),
('SCO 4', 'Escócia'),
('SCO 5', 'Escócia'),
('SCO 6', 'Escócia'),
('SCO 7', 'Escócia'),
('SCO 8', 'Escócia'),
('SCO 9', 'Escócia'),
('SCO 10', 'Escócia'),
('SCO 11', 'Escócia'),
('SCO 12', 'Escócia'),
('SCO 13', 'Escócia'),
('SCO 14', 'Escócia'),
('SCO 15', 'Escócia'),
('SCO 16', 'Escócia'),
('SCO 17', 'Escócia'),
('SCO 18', 'Escócia'),
('SCO 19', 'Escócia'),
('SCO 20', 'Escócia'),
('HAI 1', 'Haiti'),
('HAI 2', 'Haiti'),
('HAI 3', 'Haiti'),
('HAI 4', 'Haiti'),
('HAI 5', 'Haiti'),
('HAI 6', 'Haiti'),
('HAI 7', 'Haiti'),
('HAI 8', 'Haiti'),
('HAI 9', 'Haiti'),
('HAI 10', 'Haiti'),
('HAI 11', 'Haiti'),
('HAI 12', 'Haiti'),
('HAI 13', 'Haiti'),
('HAI 14', 'Haiti'),
('HAI 15', 'Haiti'),
('HAI 16', 'Haiti'),
('HAI 17', 'Haiti'),
('HAI 18', 'Haiti'),
('HAI 19', 'Haiti'),
('HAI 20', 'Haiti'),
('USA 1', 'EUA'),
('USA 2', 'EUA'),
('USA 3', 'EUA'),
('USA 4', 'EUA'),
('USA 5', 'EUA'),
('USA 6', 'EUA'),
('USA 7', 'EUA'),
('USA 8', 'EUA'),
('USA 9', 'EUA'),
('USA 10', 'EUA'),
('USA 11', 'EUA'),
('USA 12', 'EUA'),
('USA 13', 'EUA'),
('USA 14', 'EUA'),
('USA 15', 'EUA'),
('USA 16', 'EUA'),
('USA 17', 'EUA'),
('USA 18', 'EUA'),
('USA 19', 'EUA'),
('USA 20', 'EUA'),
('AUS 1', 'Austrália'),
('AUS 2', 'Austrália'),
('AUS 3', 'Austrália'),
('AUS 4', 'Austrália'),
('AUS 5', 'Austrália'),
('AUS 6', 'Austrália'),
('AUS 7', 'Austrália'),
('AUS 8', 'Austrália'),
('AUS 9', 'Austrália'),
('AUS 10', 'Austrália'),
('AUS 11', 'Austrália'),
('AUS 12', 'Austrália'),
('AUS 13', 'Austrália'),
('AUS 14', 'Austrália'),
('AUS 15', 'Austrália'),
('AUS 16', 'Austrália'),
('AUS 17', 'Austrália'),
('AUS 18', 'Austrália'),
('AUS 19', 'Austrália'),
('AUS 20', 'Austrália'),
('PAR 1', 'Paraguai'),
('PAR 2', 'Paraguai'),
('PAR 3', 'Paraguai'),
('PAR 4', 'Paraguai'),
('PAR 5', 'Paraguai'),
('PAR 6', 'Paraguai'),
('PAR 7', 'Paraguai'),
('PAR 8', 'Paraguai'),
('PAR 9', 'Paraguai'),
('PAR 10', 'Paraguai'),
('PAR 11', 'Paraguai'),
('PAR 12', 'Paraguai'),
('PAR 13', 'Paraguai'),
('PAR 14', 'Paraguai'),
('PAR 15', 'Paraguai'),
('PAR 16', 'Paraguai'),
('PAR 17', 'Paraguai'),
('PAR 18', 'Paraguai'),
('PAR 19', 'Paraguai'),
('PAR 20', 'Paraguai'),
('TUR 1', 'Turquia'),
('TUR 2', 'Turquia'),
('TUR 3', 'Turquia'),
('TUR 4', 'Turquia'),
('TUR 5', 'Turquia'),
('TUR 6', 'Turquia'),
('TUR 7', 'Turquia'),
('TUR 8', 'Turquia'),
('TUR 9', 'Turquia'),
('TUR 10', 'Turquia'),
('TUR 11', 'Turquia'),
('TUR 12', 'Turquia'),
('TUR 13', 'Turquia'),
('TUR 14', 'Turquia'),
('TUR 15', 'Turquia'),
('TUR 16', 'Turquia'),
('TUR 17', 'Turquia'),
('TUR 18', 'Turquia'),
('TUR 19', 'Turquia'),
('TUR 20', 'Turquia'),
('GER 1', 'Alemanha'),
('GER 2', 'Alemanha'),
('GER 3', 'Alemanha'),
('GER 4', 'Alemanha'),
('GER 5', 'Alemanha'),
('GER 6', 'Alemanha'),
('GER 7', 'Alemanha'),
('GER 8', 'Alemanha'),
('GER 9', 'Alemanha'),
('GER 10', 'Alemanha'),
('GER 11', 'Alemanha'),
('GER 12', 'Alemanha'),
('GER 13', 'Alemanha'),
('GER 14', 'Alemanha'),
('GER 15', 'Alemanha'),
('GER 16', 'Alemanha'),
('GER 17', 'Alemanha'),
('GER 18', 'Alemanha'),
('GER 19', 'Alemanha'),
('GER 20', 'Alemanha'),
('CIV 1', 'C. Marfim'),
('CIV 2', 'C. Marfim'),
('CIV 3', 'C. Marfim'),
('CIV 4', 'C. Marfim'),
('CIV 5', 'C. Marfim'),
('CIV 6', 'C. Marfim'),
('CIV 7', 'C. Marfim'),
('CIV 8', 'C. Marfim'),
('CIV 9', 'C. Marfim'),
('CIV 10', 'C. Marfim'),
('CIV 11', 'C. Marfim'),
('CIV 12', 'C. Marfim'),
('CIV 13', 'C. Marfim'),
('CIV 14', 'C. Marfim'),
('CIV 15', 'C. Marfim'),
('CIV 16', 'C. Marfim'),
('CIV 17', 'C. Marfim'),
('CIV 18', 'C. Marfim'),
('CIV 19', 'C. Marfim'),
('CIV 20', 'C. Marfim'),
('ECU 1', 'Equador'),
('ECU 2', 'Equador'),
('ECU 3', 'Equador'),
('ECU 4', 'Equador'),
('ECU 5', 'Equador'),
('ECU 6', 'Equador'),
('ECU 7', 'Equador'),
('ECU 8', 'Equador'),
('ECU 9', 'Equador'),
('ECU 10', 'Equador'),
('ECU 11', 'Equador'),
('ECU 12', 'Equador'),
('ECU 13', 'Equador'),
('ECU 14', 'Equador'),
('ECU 15', 'Equador'),
('ECU 16', 'Equador'),
('ECU 17', 'Equador'),
('ECU 18', 'Equador'),
('ECU 19', 'Equador'),
('ECU 20', 'Equador'),
('CUW 1', 'Curaçao'),
('CUW 2', 'Curaçao'),
('CUW 3', 'Curaçao'),
('CUW 4', 'Curaçao'),
('CUW 5', 'Curaçao'),
('CUW 6', 'Curaçao'),
('CUW 7', 'Curaçao'),
('CUW 8', 'Curaçao'),
('CUW 9', 'Curaçao'),
('CUW 10', 'Curaçao'),
('CUW 11', 'Curaçao'),
('CUW 12', 'Curaçao'),
('CUW 13', 'Curaçao'),
('CUW 14', 'Curaçao'),
('CUW 15', 'Curaçao'),
('CUW 16', 'Curaçao'),
('CUW 17', 'Curaçao'),
('CUW 18', 'Curaçao'),
('CUW 19', 'Curaçao'),
('CUW 20', 'Curaçao'),
('NED 1', 'Holanda'),
('NED 2', 'Holanda'),
('NED 3', 'Holanda'),
('NED 4', 'Holanda'),
('NED 5', 'Holanda'),
('NED 6', 'Holanda'),
('NED 7', 'Holanda'),
('NED 8', 'Holanda'),
('NED 9', 'Holanda'),
('NED 10', 'Holanda'),
('NED 11', 'Holanda'),
('NED 12', 'Holanda'),
('NED 13', 'Holanda'),
('NED 14', 'Holanda'),
('NED 15', 'Holanda'),
('NED 16', 'Holanda'),
('NED 17', 'Holanda'),
('NED 18', 'Holanda'),
('NED 19', 'Holanda'),
('NED 20', 'Holanda'),
('JPN 1', 'Japão'),
('JPN 2', 'Japão'),
('JPN 3', 'Japão'),
('JPN 4', 'Japão'),
('JPN 5', 'Japão'),
('JPN 6', 'Japão'),
('JPN 7', 'Japão'),
('JPN 8', 'Japão'),
('JPN 9', 'Japão'),
('JPN 10', 'Japão'),
('JPN 11', 'Japão'),
('JPN 12', 'Japão'),
('JPN 13', 'Japão'),
('JPN 14', 'Japão'),
('JPN 15', 'Japão'),
('JPN 16', 'Japão'),
('JPN 17', 'Japão'),
('JPN 18', 'Japão'),
('JPN 19', 'Japão'),
('JPN 20', 'Japão'),
('SWE 1', 'Suécia'),
('SWE 2', 'Suécia'),
('SWE 3', 'Suécia'),
('SWE 4', 'Suécia'),
('SWE 5', 'Suécia'),
('SWE 6', 'Suécia'),
('SWE 7', 'Suécia'),
('SWE 8', 'Suécia'),
('SWE 9', 'Suécia'),
('SWE 10', 'Suécia'),
('SWE 11', 'Suécia'),
('SWE 12', 'Suécia'),
('SWE 13', 'Suécia'),
('SWE 14', 'Suécia'),
('SWE 15', 'Suécia'),
('SWE 16', 'Suécia'),
('SWE 17', 'Suécia'),
('SWE 18', 'Suécia'),
('SWE 19', 'Suécia'),
('SWE 20', 'Suécia'),
('TUN 1', 'Tunísia'),
('TUN 2', 'Tunísia'),
('TUN 3', 'Tunísia'),
('TUN 4', 'Tunísia'),
('TUN 5', 'Tunísia'),
('TUN 6', 'Tunísia'),
('TUN 7', 'Tunísia'),
('TUN 8', 'Tunísia'),
('TUN 9', 'Tunísia'),
('TUN 10', 'Tunísia'),
('TUN 11', 'Tunísia'),
('TUN 12', 'Tunísia'),
('TUN 13', 'Tunísia'),
('TUN 14', 'Tunísia'),
('TUN 15', 'Tunísia'),
('TUN 16', 'Tunísia'),
('TUN 17', 'Tunísia'),
('TUN 18', 'Tunísia'),
('TUN 19', 'Tunísia'),
('TUN 20', 'Tunísia'),
('BEL 1', 'Bélgica'),
('BEL 2', 'Bélgica'),
('BEL 3', 'Bélgica'),
('BEL 4', 'Bélgica'),
('BEL 5', 'Bélgica'),
('BEL 6', 'Bélgica'),
('BEL 7', 'Bélgica'),
('BEL 8', 'Bélgica'),
('BEL 9', 'Bélgica'),
('BEL 10', 'Bélgica'),
('BEL 11', 'Bélgica'),
('BEL 12', 'Bélgica'),
('BEL 13', 'Bélgica'),
('BEL 14', 'Bélgica'),
('BEL 15', 'Bélgica'),
('BEL 16', 'Bélgica'),
('BEL 17', 'Bélgica'),
('BEL 18', 'Bélgica'),
('BEL 19', 'Bélgica'),
('BEL 20', 'Bélgica'),
('EGY 1', 'Egito'),
('EGY 2', 'Egito'),
('EGY 3', 'Egito'),
('EGY 4', 'Egito'),
('EGY 5', 'Egito'),
('EGY 6', 'Egito'),
('EGY 7', 'Egito'),
('EGY 8', 'Egito'),
('EGY 9', 'Egito'),
('EGY 10', 'Egito'),
('EGY 11', 'Egito'),
('EGY 12', 'Egito'),
('EGY 13', 'Egito'),
('EGY 14', 'Egito'),
('EGY 15', 'Egito'),
('EGY 16', 'Egito'),
('EGY 17', 'Egito'),
('EGY 18', 'Egito'),
('EGY 19', 'Egito'),
('EGY 20', 'Egito'),
('IRN 1', 'Irã'),
('IRN 2', 'Irã'),
('IRN 3', 'Irã'),
('IRN 4', 'Irã'),
('IRN 5', 'Irã'),
('IRN 6', 'Irã'),
('IRN 7', 'Irã'),
('IRN 8', 'Irã'),
('IRN 9', 'Irã'),
('IRN 10', 'Irã'),
('IRN 11', 'Irã'),
('IRN 12', 'Irã'),
('IRN 13', 'Irã'),
('IRN 14', 'Irã'),
('IRN 15', 'Irã'),
('IRN 16', 'Irã'),
('IRN 17', 'Irã'),
('IRN 18', 'Irã'),
('IRN 19', 'Irã'),
('IRN 20', 'Irã'),
('NZL 1', 'Nova Zelândia'),
('NZL 2', 'Nova Zelândia'),
('NZL 3', 'Nova Zelândia'),
('NZL 4', 'Nova Zelândia'),
('NZL 5', 'Nova Zelândia'),
('NZL 6', 'Nova Zelândia'),
('NZL 7', 'Nova Zelândia'),
('NZL 8', 'Nova Zelândia'),
('NZL 9', 'Nova Zelândia'),
('NZL 10', 'Nova Zelândia'),
('NZL 11', 'Nova Zelândia'),
('NZL 12', 'Nova Zelândia'),
('NZL 13', 'Nova Zelândia'),
('NZL 14', 'Nova Zelândia'),
('NZL 15', 'Nova Zelândia'),
('NZL 16', 'Nova Zelândia'),
('NZL 17', 'Nova Zelândia'),
('NZL 18', 'Nova Zelândia'),
('NZL 19', 'Nova Zelândia'),
('NZL 20', 'Nova Zelândia'),
('ESP 1', 'Espanha'),
('ESP 2', 'Espanha'),
('ESP 3', 'Espanha'),
('ESP 4', 'Espanha'),
('ESP 5', 'Espanha'),
('ESP 6', 'Espanha'),
('ESP 7', 'Espanha'),
('ESP 8', 'Espanha'),
('ESP 9', 'Espanha'),
('ESP 10', 'Espanha'),
('ESP 11', 'Espanha'),
('ESP 12', 'Espanha'),
('ESP 13', 'Espanha'),
('ESP 14', 'Espanha'),
('ESP 15', 'Espanha'),
('ESP 16', 'Espanha'),
('ESP 17', 'Espanha'),
('ESP 18', 'Espanha'),
('ESP 19', 'Espanha'),
('ESP 20', 'Espanha'),
('CPV 1', 'Cabo Verde'),
('CPV 2', 'Cabo Verde'),
('CPV 3', 'Cabo Verde'),
('CPV 4', 'Cabo Verde'),
('CPV 5', 'Cabo Verde'),
('CPV 6', 'Cabo Verde'),
('CPV 7', 'Cabo Verde'),
('CPV 8', 'Cabo Verde'),
('CPV 9', 'Cabo Verde'),
('CPV 10', 'Cabo Verde'),
('CPV 11', 'Cabo Verde'),
('CPV 12', 'Cabo Verde'),
('CPV 13', 'Cabo Verde'),
('CPV 14', 'Cabo Verde'),
('CPV 15', 'Cabo Verde'),
('CPV 16', 'Cabo Verde'),
('CPV 17', 'Cabo Verde'),
('CPV 18', 'Cabo Verde'),
('CPV 19', 'Cabo Verde'),
('CPV 20', 'Cabo Verde'),
('URU 1', 'Uruguai'),
('URU 2', 'Uruguai'),
('URU 3', 'Uruguai'),
('URU 4', 'Uruguai'),
('URU 5', 'Uruguai'),
('URU 6', 'Uruguai'),
('URU 7', 'Uruguai'),
('URU 8', 'Uruguai'),
('URU 9', 'Uruguai'),
('URU 10', 'Uruguai'),
('URU 11', 'Uruguai'),
('URU 12', 'Uruguai'),
('URU 13', 'Uruguai'),
('URU 14', 'Uruguai'),
('URU 15', 'Uruguai'),
('URU 16', 'Uruguai'),
('URU 17', 'Uruguai'),
('URU 18', 'Uruguai'),
('URU 19', 'Uruguai'),
('URU 20', 'Uruguai'),
('KSA 1', 'Arábia Saudita'),
('KSA 2', 'Arábia Saudita'),
('KSA 3', 'Arábia Saudita'),
('KSA 4', 'Arábia Saudita'),
('KSA 5', 'Arábia Saudita'),
('KSA 6', 'Arábia Saudita'),
('KSA 7', 'Arábia Saudita'),
('KSA 8', 'Arábia Saudita'),
('KSA 9', 'Arábia Saudita'),
('KSA 10', 'Arábia Saudita'),
('KSA 11', 'Arábia Saudita'),
('KSA 12', 'Arábia Saudita'),
('KSA 13', 'Arábia Saudita'),
('KSA 14', 'Arábia Saudita'),
('KSA 15', 'Arábia Saudita'),
('KSA 16', 'Arábia Saudita'),
('KSA 17', 'Arábia Saudita'),
('KSA 18', 'Arábia Saudita'),
('KSA 19', 'Arábia Saudita'),
('KSA 20', 'Arábia Saudita'),
('FRA 1', 'França'),
('FRA 2', 'França'),
('FRA 3', 'França'),
('FRA 4', 'França'),
('FRA 5', 'França'),
('FRA 6', 'França'),
('FRA 7', 'França'),
('FRA 8', 'França'),
('FRA 9', 'França'),
('FRA 10', 'França'),
('FRA 11', 'França'),
('FRA 12', 'França'),
('FRA 13', 'França'),
('FRA 14', 'França'),
('FRA 15', 'França'),
('FRA 16', 'França'),
('FRA 17', 'França'),
('FRA 18', 'França'),
('FRA 19', 'França'),
('FRA 20', 'França'),
('NOR 1', 'Noruega'),
('NOR 2', 'Noruega'),
('NOR 3', 'Noruega'),
('NOR 4', 'Noruega'),
('NOR 5', 'Noruega'),
('NOR 6', 'Noruega'),
('NOR 7', 'Noruega'),
('NOR 8', 'Noruega'),
('NOR 9', 'Noruega'),
('NOR 10', 'Noruega'),
('NOR 11', 'Noruega'),
('NOR 12', 'Noruega'),
('NOR 13', 'Noruega'),
('NOR 14', 'Noruega'),
('NOR 15', 'Noruega'),
('NOR 16', 'Noruega'),
('NOR 17', 'Noruega'),
('NOR 18', 'Noruega'),
('NOR 19', 'Noruega'),
('NOR 20', 'Noruega'),
('SEN 1', 'Senegal'),
('SEN 2', 'Senegal'),
('SEN 3', 'Senegal'),
('SEN 4', 'Senegal'),
('SEN 5', 'Senegal'),
('SEN 6', 'Senegal'),
('SEN 7', 'Senegal'),
('SEN 8', 'Senegal'),
('SEN 9', 'Senegal'),
('SEN 10', 'Senegal'),
('SEN 11', 'Senegal'),
('SEN 12', 'Senegal'),
('SEN 13', 'Senegal'),
('SEN 14', 'Senegal'),
('SEN 15', 'Senegal'),
('SEN 16', 'Senegal'),
('SEN 17', 'Senegal'),
('SEN 18', 'Senegal'),
('SEN 19', 'Senegal'),
('SEN 20', 'Senegal'),
('IRQ 1', 'Iraque'),
('IRQ 2', 'Iraque'),
('IRQ 3', 'Iraque'),
('IRQ 4', 'Iraque'),
('IRQ 5', 'Iraque'),
('IRQ 6', 'Iraque'),
('IRQ 7', 'Iraque'),
('IRQ 8', 'Iraque'),
('IRQ 9', 'Iraque'),
('IRQ 10', 'Iraque'),
('IRQ 11', 'Iraque'),
('IRQ 12', 'Iraque'),
('IRQ 13', 'Iraque'),
('IRQ 14', 'Iraque'),
('IRQ 15', 'Iraque'),
('IRQ 16', 'Iraque'),
('IRQ 17', 'Iraque'),
('IRQ 18', 'Iraque'),
('IRQ 19', 'Iraque'),
('IRQ 20', 'Iraque'),
('ARG 1', 'Argentina'),
('ARG 2', 'Argentina'),
('ARG 3', 'Argentina'),
('ARG 4', 'Argentina'),
('ARG 5', 'Argentina'),
('ARG 6', 'Argentina'),
('ARG 7', 'Argentina'),
('ARG 8', 'Argentina'),
('ARG 9', 'Argentina'),
('ARG 10', 'Argentina'),
('ARG 11', 'Argentina'),
('ARG 12', 'Argentina'),
('ARG 13', 'Argentina'),
('ARG 14', 'Argentina'),
('ARG 15', 'Argentina'),
('ARG 16', 'Argentina'),
('ARG 17', 'Argentina'),
('ARG 18', 'Argentina'),
('ARG 19', 'Argentina'),
('ARG 20', 'Argentina'),
('AUT 1', 'Áustria'),
('AUT 2', 'Áustria'),
('AUT 3', 'Áustria'),
('AUT 4', 'Áustria'),
('AUT 5', 'Áustria'),
('AUT 6', 'Áustria'),
('AUT 7', 'Áustria'),
('AUT 8', 'Áustria'),
('AUT 9', 'Áustria'),
('AUT 10', 'Áustria'),
('AUT 11', 'Áustria'),
('AUT 12', 'Áustria'),
('AUT 13', 'Áustria'),
('AUT 14', 'Áustria'),
('AUT 15', 'Áustria'),
('AUT 16', 'Áustria'),
('AUT 17', 'Áustria'),
('AUT 18', 'Áustria'),
('AUT 19', 'Áustria'),
('AUT 20', 'Áustria'),
('ALG 1', 'Argélia'),
('ALG 2', 'Argélia'),
('ALG 3', 'Argélia'),
('ALG 4', 'Argélia'),
('ALG 5', 'Argélia'),
('ALG 6', 'Argélia'),
('ALG 7', 'Argélia'),
('ALG 8', 'Argélia'),
('ALG 9', 'Argélia'),
('ALG 10', 'Argélia'),
('ALG 11', 'Argélia'),
('ALG 12', 'Argélia'),
('ALG 13', 'Argélia'),
('ALG 14', 'Argélia'),
('ALG 15', 'Argélia'),
('ALG 16', 'Argélia'),
('ALG 17', 'Argélia'),
('ALG 18', 'Argélia'),
('ALG 19', 'Argélia'),
('ALG 20', 'Argélia'),
('JOR 1', 'Jordânia'),
('JOR 2', 'Jordânia'),
('JOR 3', 'Jordânia'),
('JOR 4', 'Jordânia'),
('JOR 5', 'Jordânia'),
('JOR 6', 'Jordânia'),
('JOR 7', 'Jordânia'),
('JOR 8', 'Jordânia'),
('JOR 9', 'Jordânia'),
('JOR 10', 'Jordânia'),
('JOR 11', 'Jordânia'),
('JOR 12', 'Jordânia'),
('JOR 13', 'Jordânia'),
('JOR 14', 'Jordânia'),
('JOR 15', 'Jordânia'),
('JOR 16', 'Jordânia'),
('JOR 17', 'Jordânia'),
('JOR 18', 'Jordânia'),
('JOR 19', 'Jordânia'),
('JOR 20', 'Jordânia'),
('COL 1', 'Colômbia'),
('COL 2', 'Colômbia'),
('COL 3', 'Colômbia'),
('COL 4', 'Colômbia'),
('COL 5', 'Colômbia'),
('COL 6', 'Colômbia'),
('COL 7', 'Colômbia'),
('COL 8', 'Colômbia'),
('COL 9', 'Colômbia'),
('COL 10', 'Colômbia'),
('COL 11', 'Colômbia'),
('COL 12', 'Colômbia'),
('COL 13', 'Colômbia'),
('COL 14', 'Colômbia'),
('COL 15', 'Colômbia'),
('COL 16', 'Colômbia'),
('COL 17', 'Colômbia'),
('COL 18', 'Colômbia'),
('COL 19', 'Colômbia'),
('COL 20', 'Colômbia'),
('POR 1', 'Portugal'),
('POR 2', 'Portugal'),
('POR 3', 'Portugal'),
('POR 4', 'Portugal'),
('POR 5', 'Portugal'),
('POR 6', 'Portugal'),
('POR 7', 'Portugal'),
('POR 8', 'Portugal'),
('POR 9', 'Portugal'),
('POR 10', 'Portugal'),
('POR 11', 'Portugal'),
('POR 12', 'Portugal'),
('POR 13', 'Portugal'),
('POR 14', 'Portugal'),
('POR 15', 'Portugal'),
('POR 16', 'Portugal'),
('POR 17', 'Portugal'),
('POR 18', 'Portugal'),
('POR 19', 'Portugal'),
('POR 20', 'Portugal'),
('COD 1', 'RD Congo'),
('COD 2', 'RD Congo'),
('COD 3', 'RD Congo'),
('COD 4', 'RD Congo'),
('COD 5', 'RD Congo'),
('COD 6', 'RD Congo'),
('COD 7', 'RD Congo'),
('COD 8', 'RD Congo'),
('COD 9', 'RD Congo'),
('COD 10', 'RD Congo'),
('COD 11', 'RD Congo'),
('COD 12', 'RD Congo'),
('COD 13', 'RD Congo'),
('COD 14', 'RD Congo'),
('COD 15', 'RD Congo'),
('COD 16', 'RD Congo'),
('COD 17', 'RD Congo'),
('COD 18', 'RD Congo'),
('COD 19', 'RD Congo'),
('COD 20', 'RD Congo'),
('UZB 1', 'Uzbequistão'),
('UZB 2', 'Uzbequistão'),
('UZB 3', 'Uzbequistão'),
('UZB 4', 'Uzbequistão'),
('UZB 5', 'Uzbequistão'),
('UZB 6', 'Uzbequistão'),
('UZB 7', 'Uzbequistão'),
('UZB 8', 'Uzbequistão'),
('UZB 9', 'Uzbequistão'),
('UZB 10', 'Uzbequistão'),
('UZB 11', 'Uzbequistão'),
('UZB 12', 'Uzbequistão'),
('UZB 13', 'Uzbequistão'),
('UZB 14', 'Uzbequistão'),
('UZB 15', 'Uzbequistão'),
('UZB 16', 'Uzbequistão'),
('UZB 17', 'Uzbequistão'),
('UZB 18', 'Uzbequistão'),
('UZB 19', 'Uzbequistão'),
('UZB 20', 'Uzbequistão'),
('ENG 1', 'Inglaterra'),
('ENG 2', 'Inglaterra'),
('ENG 3', 'Inglaterra'),
('ENG 4', 'Inglaterra'),
('ENG 5', 'Inglaterra'),
('ENG 6', 'Inglaterra'),
('ENG 7', 'Inglaterra'),
('ENG 8', 'Inglaterra'),
('ENG 9', 'Inglaterra'),
('ENG 10', 'Inglaterra'),
('ENG 11', 'Inglaterra'),
('ENG 12', 'Inglaterra'),
('ENG 13', 'Inglaterra'),
('ENG 14', 'Inglaterra'),
('ENG 15', 'Inglaterra'),
('ENG 16', 'Inglaterra'),
('ENG 17', 'Inglaterra'),
('ENG 18', 'Inglaterra'),
('ENG 19', 'Inglaterra'),
('ENG 20', 'Inglaterra'),
('CRO 1', 'Croácia'),
('CRO 2', 'Croácia'),
('CRO 3', 'Croácia'),
('CRO 4', 'Croácia'),
('CRO 5', 'Croácia'),
('CRO 6', 'Croácia'),
('CRO 7', 'Croácia'),
('CRO 8', 'Croácia'),
('CRO 9', 'Croácia'),
('CRO 10', 'Croácia'),
('CRO 11', 'Croácia'),
('CRO 12', 'Croácia'),
('CRO 13', 'Croácia'),
('CRO 14', 'Croácia'),
('CRO 15', 'Croácia'),
('CRO 16', 'Croácia'),
('CRO 17', 'Croácia'),
('CRO 18', 'Croácia'),
('CRO 19', 'Croácia'),
('CRO 20', 'Croácia'),
('GHA 1', 'Gana'),
('GHA 2', 'Gana'),
('GHA 3', 'Gana'),
('GHA 4', 'Gana'),
('GHA 5', 'Gana'),
('GHA 6', 'Gana'),
('GHA 7', 'Gana'),
('GHA 8', 'Gana'),
('GHA 9', 'Gana'),
('GHA 10', 'Gana'),
('GHA 11', 'Gana'),
('GHA 12', 'Gana'),
('GHA 13', 'Gana'),
('GHA 14', 'Gana'),
('GHA 15', 'Gana'),
('GHA 16', 'Gana'),
('GHA 17', 'Gana'),
('GHA 18', 'Gana'),
('GHA 19', 'Gana'),
('GHA 20', 'Gana'),
('PAN 1', 'Panamá'),
('PAN 2', 'Panamá'),
('PAN 3', 'Panamá'),
('PAN 4', 'Panamá'),
('PAN 5', 'Panamá'),
('PAN 6', 'Panamá'),
('PAN 7', 'Panamá'),
('PAN 8', 'Panamá'),
('PAN 9', 'Panamá'),
('PAN 10', 'Panamá'),
('PAN 11', 'Panamá'),
('PAN 12', 'Panamá'),
('PAN 13', 'Panamá'),
('PAN 14', 'Panamá'),
('PAN 15', 'Panamá'),
('PAN 16', 'Panamá'),
('PAN 17', 'Panamá'),
('PAN 18', 'Panamá'),
('PAN 19', 'Panamá'),
('PAN 20', 'Panamá'),