('FWC 0', 'FWC'),
('FWC 1', 'FWC'),
('FWC 2', 'FWC'),
('FWC 3', 'FWC'),
('FWC 4', 'FWC'),
('FWC 5', 'FWC'),
('FWC 6', 'FWC'),
('FWC 7', 'FWC'),
('FWC 8', 'FWC'),
('FWC 9', 'FWC'),
('FWC 10', 'FWC'),
('FWC 11', 'FWC'),
('FWC 12', 'FWC'),
('FWC 13', 'FWC'),
('FWC 14', 'FWC'),
('FWC 15', 'FWC'),
('FWC 16', 'FWC'),
('FWC 17', 'FWC'),
('FWC 18', 'FWC'),
('FWC 19', 'FWC'),
('CC1', 'Coca-Cola'),
('CC2', 'Coca-Cola'),
('CC3', 'Coca-Cola'),
('CC4', 'Coca-Cola'),
('CC5', 'Coca-Cola'),
('CC6', 'Coca-Cola'),
('CC7', 'Coca-Cola'),
('CC8', 'Coca-Cola'),
('CC9', 'Coca-Cola'),
('CC10', 'Coca-Cola'),
('CC11', 'Coca-Cola'),
('CC12', 'Coca-Cola'),
('CC13', 'Coca-Cola'),
('CC14', 'Coca-Cola')